package at.hazm.webserver.handler

import com.twitter.io.{Buf, Reader}

import java.io.File
import java.net.URL

trait Resource {
  def lastModified: Option[Long]

  def length: Option[Long]

  def reader: Reader[Buf]
}

case class LocalFile(file: File) extends Resource {
  def lastModified: Option[Long] = Some(file.lastModified())

  def length: Option[Long] = Some(file.length())

  def reader: Reader[Buf] = Reader.fromFile(file)
}

case class GeneratedFile(autoGeneratedFile: File, sources: File*) extends Resource {
  def lastModified: Option[Long] = Some(sources.map(_.lastModified()).filter(_ > 0).max)

  def length: Option[Long] = Some(autoGeneratedFile.length())

  def reader: Reader[Buf] = Reader.fromFile(autoGeneratedFile)
}

case class URLResource(url: URL) extends Resource {
  def lastModified: Option[Long] = None

  def length: Option[Long] = None

  def reader: Reader[Buf] = Reader.fromStream(url.openStream())
}