package at.hazm.webserver.handler

import java.io.File
import java.net.URL

import com.twitter.io.Reader

trait Resource {
  def lastModified:Option[Long]
  def length:Option[Long]
  def reader:Reader
}

case class LocalFile(file:File) extends Resource {
  def lastModified = Some(file.lastModified())
  def length = Some(file.length())
  def reader:Reader = Reader.fromFile(file)
}

case class GeneratedFile(autoGeneratedFile:File, sources:File*) extends Resource {
  def lastModified = Some(sources.map(_.lastModified()).filter(_>0).max)
  def length = Some(autoGeneratedFile.length())
  def reader:Reader = Reader.fromFile(autoGeneratedFile)
}

case class URLResource(url:URL) extends Resource {
  def lastModified = None
  def length = None
  def reader:Reader = Reader.fromStream(url.openStream())
}